### ISSUE TITLE
希望可以增加删除指定上下文的功能

### ISSUE THREAD

**Issue by baiyu-yu** [MintCider/ai-interrupt#4]
群友老是给骰子强加奇怪设定，希望可以在聊天时直接通过引用那条消息让骰娘遗忘

**Comment by MintCider** [comment]
一方面需要对「引用+指令」的格式做特殊处理，另一方面需要修改数据存储结构记录 `message_id`，感觉改动太大了。v0.3.0 计划允许通过索引编号删除指定消息，先暂时这么用吧……
