### ISSUE TITLE
ai回复有缺漏，可否优化一下？

### ISSUE THREAD

**Issue by baiyu-yu** [MintCider/ai-interrupt#5]
![image](https://github.com/user-attachments/assets/8064180c-c1d0-46ce-8903-8a5cc8b8dcec)
在这种情况下换行后的语句会被切掉，佬可否有更好的方式？

**Comment by MintCider** [comment]
可以在prompt里让他一次只回一句/只回一行。我个人是这么写的：

> 一次只回复一句话，一次回复只谈一件事。

- - -

我有在考虑加入多行消息解析，比如

```text
<nickname>（<id>）：第一行
第二行
第三行
```

可以正常回复


```text
第一行
第二行
第三行
```

但是对于

```text
<nickname>（<id>）：第一行
<nickname>（<id>）：第二行
<nickname>（<id>）：第三行
```

这种情况，似乎应该去调教 API 的回复格式，因为它本来就应该只回复一次。
